name: Terraform CI/CD

on:
  push:
    paths:
      - '**/deploy_mode'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  TF_VERSION: 1.13.3

defaults:
  run:
    shell: bash

jobs:
  CI: #GitHubリポジトリのコードをCI環境に取り込みテスト
    name: "CI"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      #GitHubのシークレットに変数登録する必要あり。セキュリティ的に必須
      - name: configure aws credential
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      - name: init # init -upgradeをすることにより、GitHub Actions 上でも AWS Providerの最新化ができる
        run: |
          terraform init -no-color -upgrade

      - name: validate
        run: |
          terraform validate -no-color

      - name: plan
        run: |
          terraform plan
      # デプロイのリトライ処理。詳細はREADME.mdを参照
      - name: apply
        run: |
          for i in {1..3}; do
            terraform apply -auto-approve && break
            echo "Retry Apply"
            sleep 60
          done
  # 本番・チーム運用では非推奨　個人学習用。コスト削減を目的
  destroy:
    name: "destroy"
    runs-on: ubuntu-latest
    needs: CI
    if: failure()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: configure aws credential
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      - name: init
        run: |
          terraform init -no-color -upgrade

      - name: validate
        run: |
          terraform validate -no-color

      - name: plan
        run: |
          terraform plan

      - name: always destroy
        run: | 
          for i in {1..3}; do
            terraform destroy -auto-approve && break
            echo "Retry destroy"
            sleep 60
          done